### ISSUE TITLE
Link GOLD study IDs to JGI

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/pilot#15]
On the left hand pane can/should we link the gold study IDs (Gs*) to the JGI web pages?

**Comment by cmungall** [comment]
See also #5

**Comment by wdduncan** [comment]
Yes. This is related #5 
I was thinking more at the user interface, though.

**Comment by jeffbaumes** [comment]
You can now "Open in GOLD" when navigating to the details of the study. The fact that there is a facet in the left panel for the "id" attribute is just a result of throwing everything in there to start. I assume in the future we will remove that field from the side panel, and any other value that is unique or mostly unique in the data. Some others I see on the chopping block are "name", "description", and some other free-text data.

There will also need to be a different faceting UI for other types, such as range or binned search for numeric fields, and special UI for fields that form a hierarchy like the ecosystem fields.

**Comment by aclum** [comment]
@mslarae13 @ssarrafan @cmungall  closing this old issue since we have schema slots for GOLD study identifiers and these links are shown on the study page. Please reopen/open a new ticket if anything else is needed.
