### ISSUE TITLE
GOLD ID prefixes cause URL creation issues

### ISSUE THREAD

**Issue by dehays** [microbiomedata/pilot#48]
The client creates URLs used in anchor tags to link to the GOLD service.  But the introduction of ID prefixes causes those links to fail.  (Rather dramatically with a nice stack trace.  I've let GOLD know they might want to check the ID format and return a 404 instead.)

On the client, we want to build this:  https://gold.jgi.doe.gov/study?id=Gs0130354

and NOT this: https://gold.jgi.doe.gov/study?id=gold:Gs0130354

**Comment by jbeezley** [comment]
https://github.com/microbiomedata/nmdc-server/pull/56

**Comment by jbeezley** [comment]
I apparently don't have the ability to close issues here.
